"""Guardrails node — hallucination detection, investment-advice filtering, and disclaimer injection.

This module runs after all specialist agents complete. It performs three checks:
  1. LLM-as-judge hallucination detection: are the agent's findings grounded in
     the retrieved data / tool outputs?
  2. Regex-based investment-advice detection: does the text contain phrases that
     constitute direct buy/sell recommendations?
  3. Disclaimer injection: appends the standard financial disclaimer to the
     synthesised report text.

The `run_guardrails` function is wired as a LangGraph node and updates AgentState
in place (appending to the reducer-annotated `guardrail_flags` list).
"""

from __future__ import annotations

import json
import re
from typing import Optional

import structlog

from app.agents.base.schemas import AgentResult, GuardrailFlag
from app.agents.base.state import AgentState
from app.models.provider import ModelProvider

log = structlog.get_logger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────

FINANCIAL_DISCLAIMER = (
    "\n\n---\n"
    "**Disclaimer:** This analysis is generated by an AI system for informational "
    "purposes only. It does not constitute financial advice, an offer to buy or sell "
    "securities, or a solicitation of any investment decision. Past performance is not "
    "indicative of future results. All investments carry risk, including the possible "
    "loss of principal. Always consult a qualified, licensed financial advisor before "
    "making any investment decisions. The AI-generated content may contain errors or "
    "omissions and should not be relied upon as the sole basis for any financial decision."
)

# Phrases that indicate direct investment advice
_INVESTMENT_ADVICE_PATTERNS: list[str] = [
    r"\byou should (buy|sell|purchase|acquire|divest|short)\b",
    r"\bstrong buy\b",
    r"\bstrong sell\b",
    r"\bwill definitely\b",
    r"\bguaranteed (to|return|gain|profit)\b",
    r"\bprice target is\b",
    r"\bprice target of \$[\d,]+",
    r"\brecommend (buying|selling|purchasing|shorting)\b",
    r"\bI (recommend|advise|suggest) (buying|selling|you buy|you sell)\b",
    r"\bthis (stock|equity|share) is a (buy|sell|hold)\b",
    r"\b(buy|sell) (this|the) (stock|equity|share|position)\b",
    r"\byou (must|need to|ought to) (buy|sell|exit|enter)\b",
    r"\btime to (buy|sell|exit|enter)\b",
    r"\bexcellent (buying|selling) opportunity\b",
    r"\b(clearly|obviously|definitely) (undervalued|overvalued)\b",
    r"\bwill (rise|fall|drop|surge|collapse|skyrocket) to \$[\d,]+",
]

_COMPILED_ADVICE_PATTERNS = [
    re.compile(p, re.IGNORECASE) for p in _INVESTMENT_ADVICE_PATTERNS
]

# Hallucination-check system prompt
_HALLUCINATION_SYSTEM_PROMPT = (
    "You are a financial fact-checker. Given retrieved data and agent findings, "
    "identify claims that cannot be verified from the provided data. "
    "Be precise — only flag claims that are clearly contradicted by or absent from "
    "the retrieved data. Do not flag general analytical conclusions or interpretations "
    "that are reasonable inferences from the data. "
    "Output JSON with exactly these keys: "
    '{"grounded_claims": [...], "ungrounded_claims": [...], "hallucination_score": 0.0-1.0} '
    "where hallucination_score is 0.0 if everything is grounded and 1.0 if nothing is."
)

# ── Core functions ─────────────────────────────────────────────────────────────


async def check_hallucination(
    agent_result: AgentResult,
    retrieved_docs: list[dict],
    provider: ModelProvider,
    model: str,
) -> tuple[float, list[str]]:
    """Use an LLM judge to verify that agent findings are grounded in the evidence.

    Args:
        agent_result: The structured output from a specialist agent.
        retrieved_docs: RAG documents and tool outputs used as evidence.
        provider: Active ModelProvider instance.
        model: Model name to use for the judge call (typically fast_model to save cost).

    Returns:
        Tuple of (hallucination_score: float 0-1, ungrounded_claims: list[str]).
        A score of 0.0 means fully grounded; 1.0 means completely ungrounded.
    """
    if not agent_result.findings or not retrieved_docs:
        # Cannot assess without either findings or evidence — return neutral score
        return 0.5, ["Insufficient evidence to verify findings."]

    # Truncate retrieved docs to avoid blowing context limits
    evidence_snippets = []
    for doc in retrieved_docs[:10]:
        content = doc.get("content") or doc.get("text") or str(doc)
        evidence_snippets.append(content[:500])

    # Truncate citations to extract cited facts
    cited_facts = []
    for citation in agent_result.citations[:10]:
        if citation.excerpt:
            cited_facts.append(f"[{citation.source_type}] {citation.excerpt[:300]}")

    # Build key data points summary
    data_point_summary = []
    for dp in agent_result.key_data_points[:15]:
        unit = f" {dp.unit}" if dp.unit else ""
        data_point_summary.append(f"{dp.label}: {dp.value}{unit}")

    evidence_block = "\n\n".join([
        "=== Retrieved Documents ===",
        "\n---\n".join(evidence_snippets) if evidence_snippets else "(none)",
        "=== Cited Facts ===",
        "\n".join(cited_facts) if cited_facts else "(none)",
        "=== Key Data Points ===",
        "\n".join(data_point_summary) if data_point_summary else "(none)",
    ])

    user_message = (
        f"Agent: {agent_result.agent_name}\n\n"
        f"Agent Findings (to verify):\n{agent_result.findings[:2000]}\n\n"
        f"Available Evidence:\n{evidence_block[:3000]}"
    )

    try:
        response = await provider.complete(
            messages=[
                {"role": "system", "content": _HALLUCINATION_SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ],
            model=model,
            response_format={"type": "json_object"},
            temperature=0.0,
            max_tokens=1024,
        )
        data = json.loads(response.content)
        score = float(data.get("hallucination_score", 0.3))
        score = max(0.0, min(1.0, score))  # clamp to [0, 1]
        ungrounded = data.get("ungrounded_claims", [])
        if not isinstance(ungrounded, list):
            ungrounded = [str(ungrounded)]
        return score, ungrounded
    except (json.JSONDecodeError, ValueError, KeyError) as exc:
        log.warning("hallucination_check_parse_error", error=str(exc))
        return 0.3, []
    except Exception as exc:
        log.error("hallucination_check_error", error=str(exc))
        return 0.3, [f"Hallucination check failed: {exc}"]


def check_investment_advice(text: str) -> list[str]:
    """Regex-based scan for phrases that constitute direct investment advice.

    Args:
        text: Any free-form text to scan (findings, summaries, reports).

    Returns:
        List of matched phrases that violate the no-direct-advice policy.
        Empty list means the text is clean.
    """
    flagged: list[str] = []
    for pattern in _COMPILED_ADVICE_PATTERNS:
        matches = pattern.findall(text)
        if matches:
            # Include the full matched context (up to 120 chars) for auditability
            for match_obj in pattern.finditer(text):
                start = max(0, match_obj.start() - 20)
                end = min(len(text), match_obj.end() + 20)
                context = text[start:end].strip()
                flagged.append(f'"{context}"')
    return flagged


def inject_disclaimer(report_text: str) -> str:
    """Append the standard financial disclaimer to a report string.

    Idempotent — if the disclaimer is already present, it will not be duplicated.

    Args:
        report_text: The synthesised report text to annotate.

    Returns:
        Report text with the disclaimer appended.
    """
    disclaimer_marker = "This analysis is generated by an AI system for informational"
    if disclaimer_marker in report_text:
        return report_text  # Already injected
    return report_text + FINANCIAL_DISCLAIMER


async def run_guardrails(
    state: AgentState,
    provider: ModelProvider,
) -> AgentState:
    """LangGraph node: run all guardrail checks and populate state.

    Checks every populated agent result for:
      1. Hallucination (LLM-as-judge against retrieved_documents)
      2. Investment advice language (regex)

    Populates:
      - state["guardrail_flags"]: list of GuardrailFlag instances
      - state["hallucination_score"]: max hallucination score across all agents

    Args:
        state: Current AgentState (read from LangGraph checkpoint).
        provider: Active ModelProvider for the hallucination judge call.

    Returns:
        Updated AgentState with guardrail results populated.
    """
    from app.config import get_settings

    settings = get_settings()
    # Use the fast model for guardrail judgement to minimise latency and cost
    judge_model = settings.fast_model

    retrieved_docs: list[dict] = state.get("retrieved_documents", []) or []

    # Collect all agent results that have been populated
    agent_results: list[tuple[str, Optional[AgentResult]]] = [
        ("market_research", state.get("market_research_result")),
        ("sentiment", state.get("sentiment_result")),
        ("fundamental", state.get("fundamental_result")),
        ("technical", state.get("technical_result")),
        ("risk", state.get("risk_result")),
        ("options", state.get("options_result")),
    ]

    new_flags: list[GuardrailFlag] = []
    max_hallucination_score: float = 0.0

    for agent_name, result in agent_results:
        if result is None:
            continue

        log.debug("guardrails_checking_agent", agent=agent_name)

        # ── 1. Investment-advice check ─────────────────────────────────────
        advice_hits = check_investment_advice(result.findings)
        for hit in advice_hits:
            new_flags.append(GuardrailFlag(
                flag_type="investment_advice",
                agent=agent_name,
                detail=f"Possible direct investment advice detected: {hit}",
                severity="warning",
            ))
            log.warning(
                "guardrail_investment_advice",
                agent=agent_name,
                hit=hit,
            )

        # ── 2. Confidence check ────────────────────────────────────────────
        if result.confidence < 0.3:
            new_flags.append(GuardrailFlag(
                flag_type="low_confidence",
                agent=agent_name,
                detail=(
                    f"Agent self-reported confidence is low ({result.confidence:.2f}). "
                    "Findings may be unreliable due to missing or stale data."
                ),
                severity="warning",
            ))

        # ── 3. Missing citations check ─────────────────────────────────────
        if not result.citations and result.confidence > 0.4:
            new_flags.append(GuardrailFlag(
                flag_type="missing_citation",
                agent=agent_name,
                detail="Agent returned findings with no citations despite moderate/high confidence.",
                severity="warning",
            ))

        # ── 4. Data availability check ─────────────────────────────────────
        if not result.key_data_points:
            new_flags.append(GuardrailFlag(
                flag_type="data_unavailable",
                agent=agent_name,
                detail="Agent returned no key data points — findings may lack quantitative grounding.",
                severity="warning",
            ))

        # ── 5. Hallucination check (LLM-as-judge) ─────────────────────────
        try:
            h_score, ungrounded = await check_hallucination(
                agent_result=result,
                retrieved_docs=retrieved_docs,
                provider=provider,
                model=judge_model,
            )
            max_hallucination_score = max(max_hallucination_score, h_score)

            if h_score > 0.4:
                detail = (
                    f"Hallucination score {h_score:.2f}. "
                    f"Potentially ungrounded claims: {'; '.join(ungrounded[:3])}"
                    if ungrounded
                    else f"Hallucination score {h_score:.2f}."
                )
                new_flags.append(GuardrailFlag(
                    flag_type="hallucination",
                    agent=agent_name,
                    detail=detail,
                    severity="error" if h_score > 0.7 else "warning",
                ))
                log.warning(
                    "guardrail_hallucination",
                    agent=agent_name,
                    score=h_score,
                    ungrounded_count=len(ungrounded),
                )
        except Exception as exc:
            log.error("guardrail_hallucination_check_failed", agent=agent_name, error=str(exc))
            # Do not fail the pipeline — just record a flag
            new_flags.append(GuardrailFlag(
                flag_type="hallucination",
                agent=agent_name,
                detail=f"Hallucination check could not be completed: {exc}",
                severity="warning",
            ))

    # ── Write back to state ────────────────────────────────────────────────────
    # LangGraph's reducer (_append_list) will merge these with any existing flags
    updated_state = dict(state)
    updated_state["guardrail_flags"] = new_flags
    updated_state["hallucination_score"] = max_hallucination_score
    updated_state["disclaimer_appended"] = False  # Synthesiser will call inject_disclaimer

    log.info(
        "guardrails_complete",
        new_flags=len(new_flags),
        max_hallucination_score=max_hallucination_score,
    )
    return updated_state  # type: ignore[return-value]
