"""Market data store — daily_bars and bar_coverage.

Hand-written rather than autogenerated: the existing revision covers only 5 of
the 7 pre-existing tables and the models drift from it on column types, so
--autogenerate emits spurious create_table/alter_column ops alongside the ones
we want.

Revision ID: 002
Revises: 001
Create Date: 2026-07-30
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- daily_bars ---
    op.create_table(
        "daily_bars",
        sa.Column("symbol", sa.String(16), nullable=False),
        sa.Column("bar_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("adj_close", sa.Float(), nullable=True),
        # BigInteger: crypto and index daily volumes overflow int4.
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", "bar_date"),
    )
    # The PK btree already serves "one symbol over a date range"; this serves
    # breadth's "every symbol on a single date".
    op.create_index("ix_daily_bars_bar_date", "daily_bars", ["bar_date"])

    # --- bar_coverage ---
    op.create_table(
        "bar_coverage",
        sa.Column("symbol", sa.String(16), nullable=False),
        sa.Column("first_bar_date", sa.Date(), nullable=True),
        sa.Column("last_bar_date", sa.Date(), nullable=True),
        sa.Column("bar_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "requested_span", sa.String(8), nullable=False, server_default="2y"
        ),
        sa.Column("last_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_index(
        "ix_bar_coverage_last_refresh", "bar_coverage", ["last_refresh_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_bar_coverage_last_refresh", table_name="bar_coverage")
    op.drop_table("bar_coverage")
    op.drop_index("ix_daily_bars_bar_date", table_name="daily_bars")
    op.drop_table("daily_bars")
